Symfony/src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[NotBlank(message: 'Название статьи должно содержать не менее 3 символов')]
    #[Length(min: 3)]
    private ?string $title = null;

    #[ORM\Column(length: 100, unique: true)]
    #[Gedmo\Slug(fields: ['title'])]
    private ?string $slug = null;

    #[ORM\Column(length: 100)]
    #[NotBlank(message: 'Минимум 1 слово, Максиму 100')]
    #[Length(min: 1, max: 100)]
    private ?string $description = null;

    #[ORM\Column(length: 10000)]
    #[NotBlank(message: 'Содержание статьи не должно быть пустое')]
    private ?string $body = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $keywords = null;

    #[ORM\Column(nullable: true)]
    private ?int $voteCount = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageFilename = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $publishedAt = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Comment::class, fetch: 'EXTRA_LAZY')]
    #[ORM\OrderBy(['createdAt' => 'DESC'])]
    private Collection $comments;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'articles')]
    private Collection $tags;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    #[NotBlank(message: 'Поле автор не должно быть пустое')]
    private ?User $author = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getVoteCount(): ?int
    {
        return $this->voteCount;
    }

    public function setVoteCount(?int $voteCount): self
    {
        $this->voteCount = $voteCount;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getImagePath()
    {
        return 'images/' . $this->getImageFilename();
    }

    public function voteUp()
    {
        $this->setVoteCount($this->getVoteCount() + 1);
        return $this;
    }

    public function voteDown()
    {
        $this->setVoteCount($this->getVoteCount() - 1);
        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getNonDeletedComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function isPublished(): bool
    {
        return null !== $this->getPublishedAt();
    }

    #[Callback]
    public function validate(ExecutionContextInterface $context, $payload)
    {
        if (preg_match('/\d/', $this->getTitle()) === 1) {
            $context->buildViolation('Название статьи не должно содержать цифру')
                ->atPath('title')
                ->addViolation();
        }
    }
}

Symfony/src/Controller/Admin/ArticleController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Article;
use App\Form\ArticleFormType;
use App\Repository\ArticleRepository;
use App\Services\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    #[Route('/admin/articles', name: 'app_admin_articles')]
    #[IsGranted('ROLE_ADMIN_ARTICLE')]
    public function index(
        Request $request,
        ArticleRepository $articleRepository,
        PaginatorInterface $paginator,
    ) {
        $articles = $articleRepository->findAllWithSearchQuery(
            $request->query->get('q'),
        );

        $pagination = $paginator->paginate(
            $articles,
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('admin/admin_articles.html.twig', [
            'articles' => $pagination
        ]);
    }

    #[Route('/admin/article/create', name: 'app_admin_article_create')]
    #[IsGranted('ROLE_ADMIN_ARTICLE')]
    public function create(
        Request $request,
        EntityManagerInterface $em,
        FileUploader $articleFileUploader
    ): Response {
        $form = $this->createForm(ArticleFormType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Article $article */
            $article = $form->getData();

            $image = $form->get('image')->getData();

            $article->setImageFilename($articleFileUploader->uploadFile($image));

            $em->persist($article);
            $em->flush();

            $this->addFlash('flash_message', 'Статья успешно создана');

            return $this->redirectToRoute('app_admin_articles');
        }

        return $this->render('admin/article/create.html.twig', [
            'article' => $form->createView(),
            'showError' => $form->isSubmitted()
        ]);
    }

    #[Route('/admin/article/{id}/edit', name: 'app_admin_article_edit')]
    #[IsGranted('MANAGE', subject: 'article')]
    public function edit(
        Article $article,
        EntityManagerInterface $em,
        Request $request,
        FileUploader $articleFileUploader
    ): Response {
        $form = $this->createForm(ArticleFormType::class, $article);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Article $article */
            $article = $form->getData();

            /** @var UploadedFile|null $image */
            $image = $form->get('image')->getData();

            if ($image) {
                $article->setImageFilename($articleFileUploader->uploadFile($image, $article->getImageFilename()));
            }

            $em->persist($article);
            $em->flush();

            $this->addFlash('flash_message', 'Статья успешно изменена');

            return $this->redirectToRoute('app_admin_article_edit', ['id' => $article->getId()]);
        }

        return $this->render('admin/article/edit.html.twig', [
            'article' => $form->createView(),
            'showError' => $form->isSubmitted()
        ]);
    }
}

Symfony/src/Controller/Articles.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Homework\ArticleContentProviderInterface;
use App\Repository\ArticleRepository;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class Articles extends AbstractController
{
    /**
     * @Route("/", name="app_homepage")
     * @param Article $article
     * @param ArticleRepository $repository
     * @return Response
     */
    public function homepage(ArticleRepository $repository, CommentRepository $commentRepository): Response
    {
        $comments = $commentRepository->findLatest(3);

        return $this->render('articles/articles.html.twig', [
            'articles' => $repository->findByPublishBySort(),
            'comments' => $comments
        ]);
    }

    /**
     * @Route("/articles/{slug}", name="app_article_show")
     * @param Article $article
     * @return Response
     */
    public function showArticle(Article $article) : Response
    {
        return $this->render('articles/detail.html.twig', [
            'article' => $article
        ]);
    }

    /**
     * @return string[]
     */
    public function getWords(): array
    {
        return [
            'color', 'word', 'green', 'house', 'yellow',
            'read', 'car', 'cat', 'dog', 'drink'
        ];
    }

    /**
     * @Route("/api/v1/article_content/", name="app_article_content", methods="POST")
     * @param ArticleContentProviderInterface $articleContent
     * @param Request $request
     * @return Response
     */
    public function articleContent(ArticleContentProviderInterface $articleContent, Request $request): Response
    {
        $paragraphs = $request->get('paragraphs');
        $word = $request->get('word');
        $wordsCount = $request->get('wordCount');

        return new Response(json_encode(['text' => $articleContent->get($paragraphs, $word, $wordsCount)]));
    }

    /**
     * @Route("/articles/{slug}/vote/{type<up|down>}", name="app_articles_vote", methods={"POST"})
     * @param Article $article
     * @param string $type
     * @return Response
     */
    public function like(Article $article, string $type, EntityManagerInterface $em): Response
    {
        if ($type === 'up') {
            $article->voteUp();
        }

        if ($type === 'down') {
            $article->voteDown();
        }

        $em->flush();

        return $this->json(["votes" => $article->getVoteCount()]);
    }
}

Symfony/templates/articles/articles.html.twig
{% extends 'base.html.twig' %}

{% block title %} Symfony-проект {% endblock %}

{% block body %}
<div class="container">
    <div class="row">

        <div class="col-sm-12">
            <div class="row">
                <div class="col-md-12 col-xl-8">

                    {% for article in articles %}
                        <div class="article-container mb-2">
                            <div class="row no-gutters border flex-md-row p-3 mb-4 shadow-sm">
                                <div class="col-auto d-block">
                                    <img class="article-img" src="{{ article.imageFilename | imagine_filter('articles_preview') }}">
                                </div>
                                <a class="col px-4 d-flex flex-column article-item" href="{{ path('app_article_show', {slug: article.slug }) }}">
                                    <h5 class="mb-2">{{ article.title }}</h5>
                                    <div class="d-flex mb-2">
                                        <div class="text-muted align-self-center">
                                            <img class="article-author-img rounded-circle" src="https://robohash.org/{{ article.author.firstName }}.png?set=set3">
                                            {{ article.author.firstName }}
                                        </div>
                                        <div class="text-muted align-self-center ml-3">
                                            <i class="fas fa-clock size-is-"></i>
                                            {{ article.publishedAt ? article.publishedAt|ago }}
                                        </div>
                                    </div>
                                    <div class="mb-2 d-flex">
                                        <span class="badge badge-primary mr-2"><i class="fas fa-comment"></i>{{ article.nonDeletedComments|length }}</span>
                                        {% for tag in article.tags %}
                                            <span class="badge badge-pill badge-secondary mr-2">{{ tag.name }}</span>
                                        {% endfor %}
                                    </div>
                                    <div class="mb-2 text-muted">
                                        {{ article.title }}
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}

                </div>

                {{ render(controller('App\\Controller\\PartialController::renderLastComments')) }}

            </div>
        </div>
    </div>
</div>
{% endblock %}

Symfony/templates/articles/content.html.twig
{% extends 'base_content.html.twig' %}

{% block title %}Генерация контента статьи{% endblock %}

{% block content_row_class %}{{ parent() }} p-4{% endblock %}
{% block content_col_class %}p-0{% endblock %}

{% block content %}
<h1>Генерация контента статьи</h1>

<form>
    <div class="form-group">
        <label>Количество параграфов</label>
        <input
            type="text"
            class="form-control"
            name="paragraphs"
            value="{{ app.request.query.get('paragraphs') }}"
        >
    </div>
   
    <div class="form-group">
        <label>Вставляемое слово</label>
        <input
            type="text"
            class="form-control"
            name="word"
            value="{{ app.request.query.get('word') }}"
        >
    </div>
    <div class="form-group">
        <label>Количество повторений вставляемого слова</label>
        <input
            type="text"
            class="form-control"
            name="wordsCount"
            value="{{ app.request.query.get('wordsCount') }}"
        >
    </div>
    <button type="submit" class="btn btn-primary">Сгенерировать</button>
</form>

{% if (articleContent) %}
<hr>
<div>{{ articleContent|cached_markdown }}</div>
{% endif %}

{% endblock %}

Symfony/templates/articles/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ article.slug }} {% endblock %}

{% block meta %} {{ article.keywords ? article.keywords }} {% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/detail.css') }}">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="row no-gutters border flex-md-row mb-4 shadow-sm bg-white featured-border">
                    <div class="article-detail col-sm-12">
                        <div class="col-sm-12 p-2">
                            <div class="media d-flex align-content-center">
                                <a href="{{ upload_file('article_uploads', article.imageFileName) }}" target="_blank">
                                    <img
                                            class="article-detail-image align-self-start mr-3 rounded"
                                            src="{{ article.imageFilename | imagine_filter('articles_detail') }}">
                                </a>
                                <div class="media-body d-inline-block align-self-center">
                                    <h1 class="mb-2">{{ article.title }}-Symfony-проект</h1>
                                    <div class="d-flex mb-2">
                                        <div class="text-muted align-self-center">
                                            <img class="article-author-img rounded-circle mr-2" src="https://robohash.org/флекс_абсолютович.jpg?set=set3">
                                            {{ article.author.firstName }}
                                        </div>
                                        <div class="text-muted align-self-center ml-4">
                                            <i class="fas fa-clock size-is-"></i>
                                            {{ article.publishedAt ? article.publishedAt|ago }}
                                        </div>
                                    </div>
                                    <div class="mb-2 d-flex">
                                        {% for tag in article.tags %}
                                            <span class="badge badge-pill badge-secondary mr-2">{{ tag.name }}</span>
                                        {% endfor %}
                                    </div>
                                    <div class="mb-2">
                                        <div
                                                class="text-muted align-self-center article-detail-arrows"
                                                data-id="voteBlock">
                                            <span
                                                    class="{{ article.voteCount > 0 ? 'text-success' : 'text-danger'}}"
                                                    data-id="voteCount">
                                                {{ article.voteCount ? article.voteCount : 0 }}
                                            </span>
                                            <button
                                                    class="btn btn-success ml-3"
                                                    data-id="voteButton"
                                                    data-href="{{ path('app_articles_vote', {slug: article.slug, type: "up"}) }}">
                                                <i class="fas fa-arrow-up"></i>
                                            </button>
                                            <button
                                                    class="btn btn-danger"
                                                    data-id="voteButton"
                                                    data-href="{{ path('app_articles_vote', {slug: article.slug, type: "down"}) }}">
                                                <i class="fas fa-arrow-down"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="col-12 mt-2 mb-4">
                           {{ article.body|markdown_to_html }}
                        </div>


                        <div class="col-sm-12 mb-4">
                            <h3><i class="pr-3 far fa-comment text-secondary"></i>{{ article.nonDeletedComments|length }}</h3>
                            <hr>

                            <div class="row mb-4">
                                <div class="col-sm-12">
                                    <div class="comment-container align-self-start col-sm-6">
                                        <div class="form-group">
                                            <textarea class="form-control" rows="2"></textarea>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Комментировать</button>
                                    </div>
                                </div>
                            </div>

                            {% for comment in article.nonDeletedComments %}
                            <div class="row mt-2">
                                <div class="col-sm-12">
                                    <div class="media">
                                        <img class="align-self-start comment-img rounded-circle" src="{{ asset('images/profile.png') }}">
                                        <div class="media-body align-self-start col-sm-6">
                                            <b>{{ comment.authorName }}</b>
                                            <small>
                                                {{ comment.createdAt|ago }}
                                                {{ comment.deletedAt ? 'DELTED' }}
                                            </small>
                                            <br>
                                            <span class="comment">{{ comment.content }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
{% endblock %}